name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: teste
      run: echo teste
    - name: teste
      run: pwd
    - name: teste
      run: sh ./scripts/start.sh
  

   
